name: First Workflow

on:
  push:
    branches:
      - main # Runs the workflow only when pushing to the main branch

jobs:
  first-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: First steps
        run: |
          echo "Hello World!"  # Single echo to avoid redundancy
