name: Deploy to GCloud VM

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0

      - name: Install Dependencies
        run: |
          node -v
          npm install
          npm run build

      - name: Zip Files for Deployment
        run: |
          mkdir -p deploy-package
          cp -R .next public package-lock.json package.json deploy-package/
          cd deploy-package
          zip -r project.zip .

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Package to VM
        run: |
          scp -o StrictHostKeyChecking=no deploy-package/project.zip ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:${{ secrets.DEST_FOLDER }}

      - name: SSH into VM and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd ${{ secrets.DEST_FOLDER }}
            unzip -o project.zip -d frontend
            cd frontend
            npm install --omit=dev
            pm2 restart all || pm2 start npm --name "frontend" -- run start
          EOF
