name: Development workflow
on: [push]
jobs:
  test-development:
    runs-on: ubuntu-latest
    steps:
      - name: check current paths
        run: pwd
      - name: check folder files
        run: ls
