name: Development workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependancy
        run: npm i

      - name: Build project
        run: npm run build

      - name: build directory list
        run: ls -alh .next
