name: workd flow 2

on: workflow_dispatch

jobs:
  first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: test flow
        run: |
          node -v
      - name: test 2
        run: npm -v

  second-workflow:
    runs-on: ubuntu-20.04
    steps:
      - name: check os name
        run: uname
      - name: check current directory
        run: pwd
