name: workd flow 2

on: workflow_dispatch

jobs:
  first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: test flow
        run: |
          node -v
      - name: test 2
        run: npm -v
