name: Workflow Defendancy
on: workflow_dispatch
jobs:
  First-Flow:
    runs-on: ubuntu-latest
    steps:
      - name: Check os
        run: uname

      - name: Check storage
        run: free -h

  Second-Flow:
    runs-on: ubuntu-latest
    needs: [First-Flow]
    steps:
      - name: Create A file
        run: touch test-file.txt

  Third-Flow:
    runs-on: ubuntu-latest
    needs: [Second-Flow]
    steps:
      - name: Create another file
        run: touch test-2-file.txt
